#ifndef EXIT_CODES_H
#define EXIT_CODES_H
enum {
    ERR_MISSING_ARGUMENT = 1,
    ERR_NO_INPUT_FILE = 2,
    ERR_NO_SUCH_FILE = 3,
    ERR_MKDIR = 4,
    ERR_DIR = 5,
    ERR_LONG_FILENAME = 6,
    ERR_NO_FILE_EXT = 7,
    ERR_FORK = 8,
    ERR_NE_MEMORY = 9,
    ERR_EXEC = 10,
    ERR_COMILATION_FAILED = 11,
    ERR_STAT = 12,
};
#endif
